jobs:
  action:
    name: Verify
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Unit Tests
        run: ./check/verify

name: Check

on:
  schedule:
    - cron: "55 */6 * * *"
